### ISSUE TITLE
cant connect to the adress

### ISSUE THREAD

**Issue by pelos** [mwilliamson/spur.py#21]
import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect(hostname="10.32.19.206", port=22, username="root", password="Dell123")
stdin, stdout, stderr = ssh.exec_command("ls")
print type(stdin)

print stdout.readlines()
print 111111111111111111

import spur
shell = spur.SshShell(hostname="10.32.19.206", username="root", password="Dell123", port=22)
result = shell.run(["echo", "-n", "hello"])
print result.output # prints hello
print 222222222

and this is what I get. 
<class 'paramiko.channel.ChannelFile'>
[u'anaconda-ks.cfg\n', u'Desktop\n', u'Documents\n', u'Downloads\n', u'Music\n', u'Pictures\n', u'Public\n', u'Templates\n', u'Videos\n']
111111111111111111

Traceback (most recent call last):
  File "C:/Users/Demian_Kurejwowski/Desktop/monitor_machines/for_testing.py", line 29, in <module>
    result = shell.run(["echo", "-n", "hello"])
  File "C:\Python27\lib\site-packages\spur\ssh.py", line 158, in run
    return self.spawn(*args, **kwargs).wait_for_result()
  File "C:\Python27\lib\site-packages\spur\ssh.py", line 168, in spawn
    channel = self._get_ssh_transport().open_session()
  File "C:\Python27\lib\site-packages\spur\ssh.py", line 245, in _get_ssh_transport
    raise self._connection_error(error)
spur.ssh.ConnectionError: Error creating SSH connection
Original error: Server '10.32.19.206' not found in known_hosts

Process finished with exit code 1

you know what I might be doing wrong?     thanks.

**Comment by pelos** [comment]
found the missing host key parameter, sorry for that.
