### ISSUE TITLE
UnicodeDecodeError during install

### ISSUE THREAD

**Issue by zbyte64** [mwilliamson/spur.py#36]
Got the following error when trying to pip install:

```
Step 13 : RUN pip3 install -r requirements.txt
 ---> Running in 88308c270095
Collecting docker-py==1.7.0 (from -r requirements.txt (line 1))
  Downloading docker_py-1.7.0-py2.py3-none-any.whl
Collecting spur==0.3.15 (from -r requirements.txt (line 2))
  Downloading spur-0.3.15.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-t6r3jpgx/spur/setup.py", line 13, in <module>
        long_description=read("README.rst"),
      File "/tmp/pip-build-t6r3jpgx/spur/setup.py", line 7, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
      File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3190: ordinal not in range(128)
```

Perhaps we need to set the encoding when opening the file?

**Comment by opoplawski** [comment]
Same here.  Also:
~~~~~
file ./spur.py-0.3.15/README.rst
./spur.py-0.3.15/README.rst: UTF-8 Unicode text
~~~~~
The apostrophe in "be raised if the file can't be read." on line 109 is a UTF-8 character.  I suppose you could just fix that.

**Comment by mwilliamson** [comment]
Thanks for pointing it out, I've just removed the non-ASCII apostrophe in the latest version. Let me know if you still have issues!
