### ISSUE TITLE
SSH connection error for script that runs for long time

### ISSUE THREAD

**Issue by arshdeeptinna** [mwilliamson/spur.py#49]
So I have a script where I need to connect to a few nodes sequentially to run a bunch commands that can take a few hours to complete. For each node I do something like following

```
for node in nodes:
    tunnel = spur.SshShell(hostname=node, username='xyz')
    with tunnel:
        for cmd in cmds:
            result = tunnel.run(cmd)
           do_something()
```
I run the above script in a screen session. The issue I am seeing is that all commands are run succesfully for first node but after that following exception is raised

```
Original error: No authentication methods available
Traceback (most recent call last):
  File "xyz.py", line 219, in <module>
    main()
  File "xyz.py", line 55, in __init__
    self.nodes = self.get_nodes_info()
  File xyz, line 63, in get_nodes_info
    tunnel = ssh_tunnel(str(self.seed_ip))
  File "xyy", line 29, in ssh_tunnel
    tunnel.run(["uptime"])
  File "/usr/local/lib/python2.7/dist-packages/spur/ssh.py", line 162, in run
    return self.spawn(*args, **kwargs).wait_for_result()
  File "/usr/local/lib/python2.7/dist-packages/spur/ssh.py", line 173, in spawn
    channel = self._get_ssh_transport().open_session()
  File "/usr/local/lib/python2.7/dist-packages/spur/ssh.py", line 251, in _get_ssh_transport
    raise self._connection_error(error)
spur.ssh.ConnectionError: Error creating SSH connection
Original error: No authentication methods available
```

I also noticed that in this same screen session I can not use spur at all. Even in python interpreter keep on hitting the same error. However I can connect to the same node in a different screen session. It seems like  the fact that commands take a long time to complete and thus need to keep session active for a long time messes up spur or paramiko.

Another scenario that I tried was to open a different screen session and replaced the commands that I need to run with simpler bash commands. In this case the commands were executed on all nodes without any issues.

**Comment by mwilliamson** [comment]
Hmm, spur is a pretty thin wrapper around paramiko, so I suspect paramiko has the same issue. Why output do you get if you turn on the debugging output?

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by arshdeeptinna** [comment]
```
paramiko.transport: DEBUG    starting thread (client mode): 0xa339f590L
paramiko.transport: INFO     Connected (version 2.0, client OpenSSH_6.6.1p1)
paramiko.transport: DEBUG    kex algos:[u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ssh-dss', u'ecdsa-sha2-nistp256'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
paramiko.transport: DEBUG    Ciphers agreed: local=aes128-ctr, remote=aes128-ctr
paramiko.transport: DEBUG    using kex diffie-hellman-group14-sha1; server key type ssh-rsa; cipher: local aes128-ctr, remote aes128-ctr; mac: local hmac-sha1, remote hmac-sha1; compression: local none, remote none
paramiko.transport: DEBUG    Switch to new keys ...
paramiko.transport: DEBUG    EOF in transport thread
root        : ERROR    Error creating SSH connection
Original error: No authentication methods available
```

**Comment by mwilliamson** [comment]
What does a successful run look like?

**Comment by arshdeeptinna** [comment]
```
paramiko.transport: DEBUG    starting thread (client mode): 0x9303c550L
paramiko.transport: INFO     Connected (version 2.0, client OpenSSH_6.6.1p1)
paramiko.transport: DEBUG    kex algos:[u'curve25519-sha256@libssh.org', u'ecdh-sha2-nistp256', u'ecdh-sha2-nistp384', u'ecdh-sha2-nistp521', u'diffie-hellman-group-exchange-sha256', u'diffie-hellman-group-exchange-sha1', u'diffie-hellman-group14-sha1', u'diffie-hellman-group1-sha1'] server key:[u'ssh-rsa', u'ssh-dss', u'ecdsa-sha2-nistp256'] client encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] server encrypt:[u'aes128-ctr', u'aes192-ctr', u'aes256-ctr', u'arcfour256', u'arcfour128', u'aes128-gcm@openssh.com', u'aes256-gcm@openssh.com', u'chacha20-poly1305@openssh.com', u'aes128-cbc', u'3des-cbc', u'blowfish-cbc', u'cast128-cbc', u'aes192-cbc', u'aes256-cbc', u'arcfour', u'rijndael-cbc@lysator.liu.se'] client mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] server mac:[u'hmac-md5-etm@openssh.com', u'hmac-sha1-etm@openssh.com', u'umac-64-etm@openssh.com', u'umac-128-etm@openssh.com', u'hmac-sha2-256-etm@openssh.com', u'hmac-sha2-512-etm@openssh.com', u'hmac-ripemd160-etm@openssh.com', u'hmac-sha1-96-etm@openssh.com', u'hmac-md5-96-etm@openssh.com', u'hmac-md5', u'hmac-sha1', u'umac-64@openssh.com', u'umac-128@openssh.com', u'hmac-sha2-256', u'hmac-sha2-512', u'hmac-ripemd160', u'hmac-ripemd160@openssh.com', u'hmac-sha1-96', u'hmac-md5-96'] client compress:[u'none', u'zlib@openssh.com'] server compress:[u'none', u'zlib@openssh.com'] client lang:[u''] server lang:[u''] kex follows?False
paramiko.transport: DEBUG    Ciphers agreed: local=aes128-ctr, remote=aes128-ctr
paramiko.transport: DEBUG    using kex diffie-hellman-group14-sha1; server key type ssh-rsa; cipher: local aes128-ctr, remote aes128-ctr; mac: local hmac-sha1, remote hmac-sha1; compression: local none, remote none
paramiko.transport: DEBUG    Switch to new keys ...
paramiko.transport: DEBUG    Trying SSH agent key b195f2b6f49212ae70cc400ba0e1e404
paramiko.transport: DEBUG    userauth is OK
paramiko.transport: INFO     Authentication (publickey) failed.
paramiko.transport: DEBUG    Trying SSH agent key 2b131c42b5127ffdddaf22df847d3a3f
paramiko.transport: DEBUG    userauth is OK
paramiko.transport: INFO     Authentication (publickey) successful!
paramiko.transport: DEBUG    [chan 0] Max packet in: 32768 bytes
paramiko.transport: DEBUG    [chan 0] Max packet out: 32768 bytes
paramiko.transport: DEBUG    Secsh channel 0 opened.
paramiko.transport: DEBUG    [chan 0] Sesch channel 0 request ok
paramiko.transport: DEBUG    [chan 0] EOF received (0)
paramiko.transport: DEBUG    [chan 1] Max packet in: 32768 bytes
paramiko.transport: DEBUG    [chan 0] EOF sent (0)
paramiko.transport: DEBUG    [chan 1] Max packet out: 32768 bytes
paramiko.transport: DEBUG    Secsh channel 1 opened.
paramiko.transport: DEBUG    [chan 1] Sesch channel 1 request ok
paramiko.transport: DEBUG    [chan 2] Max packet in: 32768 bytes
paramiko.transport: DEBUG    [chan 1] EOF received (1)
paramiko.transport: DEBUG    [chan 1] EOF sent (1)
paramiko.transport: DEBUG    [chan 2] Max packet out: 32768 bytes
paramiko.transport: DEBUG    Secsh channel 2 opened.
paramiko.transport: DEBUG    [chan 2] Sesch channel 2 request ok
root        : INFO     All nodes healthy. Proceeding with repairs...
paramiko.transport: DEBUG    [chan 2] EOF received (2)
paramiko.transport: DEBUG    starting thread (client mode): 0x9303c2d0L
paramiko.transport: INFO     Connected (version 2.0, client OpenSSH_6.6.1p1)
```

**Comment by mwilliamson** [comment]
Hmm, looks like it isn't finding the keys from SSH agent. Not sure why though -- you're probably better off asking wherever it is that people ask questions about Paramiko, since this doesn't seem specific to Spur.

**Comment by arshdeeptinna** [comment]
After lot of debugging and readling online, it turns out that it was just me not doing the right thing.

**Comment by mwilliamson** [comment]
Glad to hear you got it sorted out. Anything that would be useful to mention in case anybody else has a similar issue?

**Comment by arshdeeptinna** [comment]
Not really. I just didn't completely understand how ssh keys are used in proxy login.
